//
//  MotionPermissionManager.swift
//  GliderTrackerWatchApp
//
//  Auto-generated by OpenAI on 2025-07-02.
//
import Foundation
import CoreMotion

/// Triggers motion permission registration exactly once.
final class MotionPermissionManager: ObservableObject {
    private let pedometer = CMPedometer()

    func requestIfNeeded() {
        guard CMPedometer.isStepCountingAvailable() else { return }

        if CMPedometer.authorizationStatus() == .notDetermined {
            pedometer.queryPedometerData(from: Date(), to: Date()) { _, _ in }
        }
    }
}
